### PR TITLE
reorg of book

### PR DESCRIPTION
**Pull request by robkooper**
Cleaned the book up a bit.

### CODE REVIEW

**Comment by robkooper** [comment]
You can see the result at: http://isda.ncsa.illinois.edu/~kooper/PEcAn/book/

Specifically I wanted to have an easy to find models section: http://isda.ncsa.illinois.edu/~kooper/PEcAn/book/models/models.html

**Comment by mdietze** [comment]
Links to the individual model pages from the overall model table don't go anywhere. I think links in the table need to be updated.

**Comment by robkooper** [comment]
Should be fixed now.
http://isda.ncsa.illinois.edu/~kooper/PEcAn/book/models/

**Comment by robkooper** [comment]
Lots of models are missing information but was trying to have a consisted way of setting up model information pages.

I would like to do something similar with data so we can in this book also give credit to the different data providers and make it easy to find out what data there is.

**Comment by robkooper** [comment]
Another thing maybe to do is add all the models we are planning on so we have a list somewhere.

**Comment by mdietze** [comment]
I've been trying to create model-specific issues tagged with the New Model tag, but it's definitely an incomplete list. Not sure we want those models in the documentation until we actually start working on them.

**Pull request merged**
